export const ITEMS = [
  {
    id: "statue1",
    name: "The Runner",
    category: "Sculpture",
    year: "2nd Century AD",
    material: "Bronze cast",
    dimensions: "42 × 18 × 30 cm",
    description: "A dynamic bronze figure caught mid-stride, embodying speed and athletic grace. The intricate surface detailing reveals the sculptor's mastery of human anatomy in motion. Originally discovered in the ruins of a Roman bathhouse, this piece has become one of the gallery's most prized acquisitions.",
    price: "€ 24,000",
    modelUrl: "/models/statue1.glb",
    // polar (phi) and azimuthal (theta) angles in the panorama sphere
    hotspot: { phi: 1.5, theta: 0.4 },
  },
  {
    id: "statue2",
    name: "Eternal Gaze",
    category: "Sculpture",
    year: "Renaissance, ~1510",
    material: "Carrara marble",
    dimensions: "65 × 24 × 22 cm",
    description: "Carved from the same quarry that supplied Michelangelo, this bust captures a pensive figure lost in contemplation. The smooth marble surface transitions seamlessly from polished face to rough-hewn base, a deliberate juxtaposition of refinement and raw nature.",
    price: "€ 58,000",
    modelUrl: "/models/statue2.glb",
    hotspot: { phi: 1.5, theta: 1.6 },
  },
  {
    id: "statue3",
    name: "The Sentinel",
    category: "Sculpture",
    year: "Contemporary, 2019",
    material: "Cast iron, patina",
    dimensions: "120 × 40 × 38 cm",
    description: "Standing nearly a metre tall, The Sentinel commands its space with quiet authority. Cast iron was chosen for its raw industrial quality, contrasting with the classical subject matter. The green patina was achieved through a 14-month outdoor weathering process before the piece entered the collection.",
    price: "€ 31,500",
    modelUrl: "/models/statue3.glb",
    hotspot: { phi: 1.5, theta: 3.0 },
  },
  {
    id: "frame1",
    name: "Coastal Reverie",
    category: "Framed Work",
    year: "1887",
    material: "Oil on canvas, gilded frame",
    dimensions: "90 × 120 cm",
    description: "Painted during the artist's summer residency on the Normandy coast, this luminous seascape captures the fleeting quality of afternoon light on water. The gilded frame, original to the work, features hand-carved acanthus leaf motifs. Exhibited at the Paris Salon of 1888.",
    price: "€ 42,000",
    modelUrl: "/models/frame1.glb",
    hotspot: { phi: 1.4, theta: -1.2 },
  },
  {
    id: "frame2",
    name: "Portrait in Blue",
    category: "Framed Work",
    year: "1923",
    material: "Gouache on board, ebony frame",
    dimensions: "55 × 45 cm",
    description: "An intimate portrait from the post-war period, rendered in the artist's signature cool palette of prussian blues and muted greys. The subject's direct gaze challenges the viewer while the loose, expressive brushwork speaks to the emotional turbulence of the era. A rare early work.",
    price: "€ 19,800",
    modelUrl: "/models/frame2.glb",
    hotspot: { phi: 1.4, theta: -2.8 },
  },
  {
    id: "frame3",
    name: "Abstract No. 7",
    category: "Framed Work",
    year: "1961",
    material: "Mixed media on linen",
    dimensions: "200 × 150 cm",
    description: "The largest work in the collection, this monumental abstract canvas was created during the artist's New York period under the influence of the Abstract Expressionist movement. Layers of poured paint, gestural marks and collaged newspaper fragments create a rich visual archaeology.",
    price: "€ 87,000",
    modelUrl: "/models/frame3.glb",
    hotspot: { phi: 1.4, theta: 2.2 },
  },
];
